apiVersion: v1
kind: Pod
metadata:
   name: frontend
   lables:
      project: roboshop
      component: frontend
      environment: dev
      version: v1
spec:
   containers:
    - name: frontend
      image: nginx