apiVersion: v1
kind: Pod
metadata:
    name: annotations
    annotations:
       jenkins-url: "http://jenkins.com"
       imageregistry: "http://dockerhub.com"
spec:
  containers:
  - name: nginx
    image: nginx
