apiVersion: v1
kind: Pod
metadata:
   name: nginx-np 
spec:
   type: NodePort
   selector:
      project: roboshop
      component: frontend
      environment: dev
      purpose: node-port
   ports:
     - protocol: TCP
       port: 80 # service port
       targetPort: 9376 # container port