apiVersion: v1
kind: Pod
metadata:
   name: nginx-lb 
spec:
   type: LoadBalancer
   selector:
      project: roboshop
      component: frontend
      environment: dev
      purpose: load-balancer
   ports:
     - protocol: TCP
       port: 80 # service port
       targetPort: 9376 # container port
       nodePort: 30007